---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: operator-lifecycle-manager-crds
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./base/olm/crds
  prune: true
  validation: client

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: operator-lifecycle-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: operator-lifecycle-manager-crds
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./base/olm/install
  prune: true
  validation: client
