name: CI Tests

on:
  pull_request:
    branches: [main]

jobs:
  e2e:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  finalizer:
    name: Passed all CI tests
    if: always()
    runs-on: ubuntu-latest
    needs: [e2e]
    steps:
      - name: All tests passed successfully ✅
        if: needs.e2e.result == 'success'
        run: exit 0

      - name: Some tests failed ❌
        if: needs.e2e.result != 'success'
        run: exit 1
