---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: operators
  namespace: flux-system
spec:
  dependsOn:
    - name: operator-lifecycle-manager
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./base/operators
  prune: true
  validation: client
