apiVersion: v1
kind: Namespace
metadata:
  name: charts
spec: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: charts
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
