name: CI Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  IMPORT_KEYS_DIR: "./tools/keys"
  FORCE_INSTALL: 1
  FORCE_VERIFY_DOWNLOAD: 1

jobs:
  # ---------------------------------------------------------------------------------------------------------------------
  # Dynamic matrix
  # Compute how subsequent jobs will run in parallel
  # ---------------------------------------------------------------------------------------------------------------------
  matrix:
    name: Generate modules matrix
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.modules.outputs.matrix }}
      templates: ${{ steps.templates.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2

      - id: modules
        name: Get Terraform modules for integration testing
        run: echo "::set-output name=matrix::[$(matrix=($(ls -d modules/*/)); printf '"%s",' "${matrix[@]}")]"

      - id: templates
        name: Get Terraform modules/templates for unit testing
        run: echo "::set-output name=matrix::[$(matrix=($(ls -d templates/*/)); printf '"%s",' "${matrix[@]}")]"

  # ---------------------------------------------------------------------------------------------------------------------
  # Unit testing
  # Static code analysis, linting, security scanning, dry-runs
  # No real resources are deployed
  # ---------------------------------------------------------------------------------------------------------------------
  unit-modules:
    name: Unit test
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: ${{fromJSON(needs.matrix.outputs.modules)}}
    env:
      DIR: ${{ matrix.path }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - if: github.event_name == 'pull_request'
        id: changed
        continue-on-error: true
        name: Check if ${{ matrix.path }} has changed
        run: "! git diff --quiet HEAD~1 HEAD -- $DIR"

      - if: github.event_name == 'push' || steps.changed.outcome == 'success'
        name: Validate Terraform configuration files
        run: ./tools/tfvalidate.sh $DIR

  unit-templates:
    name: Unit test
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: ${{fromJSON(needs.matrix.outputs.templates)}}
    env:
      DIR: ${{ matrix.path }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - if: github.event_name == 'pull_request'
        id: changed
        continue-on-error: true
        name: Check if ${{ matrix.path }} has changed
        run: "! git diff --quiet HEAD~1 HEAD -- $DIR"

      - if: (github.event_name == 'push' || steps.changed.outcome == 'success') && contains(matrix.path, '-ops')
        name: Validate Kubernetes configuration files
        run: ./tools/kubevalidate.sh $DIR

      - if: (github.event_name == 'push' || steps.changed.outcome == 'success') && contains(matrix.path, '-infra')
        name: Validate Terraform configuration files
        run: ./tools/tfvalidate.sh $DIR
        env:
          SKIP_TERRAFORM_VALIDATE: 1

  # ---------------------------------------------------------------------------------------------------------------------
  # Integration testing
  # Real resources are deployed
  # Doesn't run for PRs from forked repositories for security reasons
  # ---------------------------------------------------------------------------------------------------------------------
  integration:
    name: Integration test
    if: github.event_name == 'push' || (github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]')
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: ${{fromJSON(needs.matrix.outputs.modules)}}
    env:
      DIR: ${{ matrix.path }}
      # TF_VAR_organization_name: ${{ secrets.CI_GITHUB_OWNER }}
      # TF_VAR_cloud_default_provider: linode
      # TF_VAR_tfe_oauth_token_id: ${{ secrets.CI_TFE_OAUTH_TOKEN_ID }}
      # TF_VAR_vcs_write_token: '{ github="${{ secrets.CI_GITHUB_TOKEN }}" }'
      # TF_VAR_sensitive_inputs: '{ my_other_secret = "This is marked as sensitive" }'
      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
      GITHUB_OWNER: ${{ secrets.CI_GITHUB_OWNER }}
      LINODE_TOKEN: ${{ secrets.CI_LINODE_TOKEN }}
      DIGITALOCEAN_TOKEN: ${{ secrets.CI_DIGITALOCEAN_TOKEN }}
      TFE_TOKEN: ${{ secrets.CI_TFE_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Test Terraform module
        run: ./tools/tftest.sh $DIR

  # ---------------------------------------------------------------------------------------------------------------------
  # Finalizers
  # These are used to determine how successful was each test suite
  # It simplifies management of required status checks
  # ---------------------------------------------------------------------------------------------------------------------
  unit-finalizer:
    name: Passed all unit tests
    if: always()
    runs-on: ubuntu-latest
    needs: [unit-modules, unit-templates]
    steps:
      - name: All tests passed successfully ✅
        if: needs.unit-modules.result == 'success' && needs.unit-templates.result == 'success'
        run: exit 0

      - name: Some tests failed ❌
        if: needs.unit-modules.result != 'success' || needs.unit-templates.result != 'success'
        run: exit 1

  integration-finalizer:
    name: Passed all integration tests
    if: always()
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - name: All tests passed successfully ✅
        if: needs.integration.result == 'success'
        run: exit 0

      - name: Integration testing was skipped
        if: needs.integration.result == 'skipped'
        run: exit 0

      - name: Some tests failed ❌
        if: needs.integration.result != 'success' && needs.integration.result != 'skipped'
        run: exit 1

  e2e-finalizer:
    name: Passed all end-to-end tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: E2E testing is part of integration testing
        run: exit 0

  finalizer:
    name: Passed all CI tests
    if: always()
    runs-on: ubuntu-latest
    needs: [unit-finalizer, integration-finalizer, e2e-finalizer]
    steps:
      - name: All tests passed successfully ✅
        if: needs.unit-finalizer.result == 'success' && needs.integration-finalizer.result == 'success' && needs.e2e-finalizer.result == 'success'
        run: exit 0

      - name: Some tests failed ❌
        if: needs.unit-finalizer.result != 'success' || needs.integration-finalizer.result != 'success' || needs.e2e-finalizer.result != 'success'
        run: exit 1
